### ISSUE TITLE
Tighten support for "jsx" form

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-react-jsx#3]
This plugin has a "jsx form" like:

``` html
<div>Hello world</div>
```

that is not like a normal JavaScript file. However it is a false positive in files without an export like:
## foo.jsx

```
import Bar from './bar';
```

Which will throw. Maybe check for imports as well?

**Comment by christopherjbaker** [comment]
The current check is that the first character is a `<`, changed in 6fd49c88b9d14863bd81cd84846f5149a86ef1cc.  Is that sufficient to close this issue?

**Comment by matthewp** [comment]
Sure!
