### ISSUE TITLE
rename this repo to steal-react-jsx

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-react-jsx#4]
this steal extension is not going to transpile JSX.
this extension use babel to transpile a special sort of JSX. the "react jsx"

babel cant transpile this `hello world` example in jsx into javascript

```
class _Main {
  static function main(args : string[]) :void {
    log "Hello, world!";
  }
}
```

@matthewp let me know if you are with me, and we rename this repo. so users aren't confused if jsx is not working.

**Comment by matthewp** [comment]
Sounds good to me.

**Comment by klepon** [comment]
it's still confusing, i thought this for importing react in jsx file. 
And it not work
so what is this plugin use for?

**Comment by pYr0x** [comment]
@klepon as the readme said, you can import jsx files with steal
`import renderer from "my-jsx-template.jsx";`
pls look into this PR https://github.com/stealjs/steal-react-jsx/pull/6

@matthewp we should make a major release, now steal 1.x is landed

**Comment by matthewp** [comment]
@pYr0x do you have an npm account? if so I can make you owner of the package and you can release as needed.

**Comment by pYr0x** [comment]
Yep
https://www.npmjs.com/~juk3

**Comment by matthewp** [comment]
@pYr0x added you!
