### ISSUE TITLE
Relative imports produce an error

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal-react-jsx#8]
I'm creating a React version of the auth-component.  When I load a .less file from within a .jsx file, the file path gets messed up.  When I try to load a `.less` file in the same subfolder `import './buttons.less'`, which should be at `http://localhost:8080/src/react/buttons/buttons.less`, for some reason it tries to find the file in the project main directory at `http://localhost:8080/src/buttons.less`.

I have a branch of the auth-component for checking out the setup.  Here's the demo page I'm loading.  https://github.com/icanjs/auth-component/blob/react/src/react/buttons/buttons.html  Maybe it's a problem with my demo page, or the [package.json](https://github.com/icanjs/auth-component/blob/react/package.json).

Open an `http-server` in the root of that repo, then open http://localhost:8080/src/react/buttons/buttons.html to see the error.

![screen shot 2016-12-18 at 10 39 39 pm](https://cloud.githubusercontent.com/assets/128857/21302295/e6cfdc74-c572-11e6-8b5a-38a2ca4d5e32.jpg)

**Comment by marshallswain** [comment]
Hmm, it seems to be more of a problem with importing a relative link, because I have the same problem when I import a `.js` file up a level, like `import '../button'`.  Maybe it's a config problem?

**Comment by matthewp** [comment]
I'm not sure if anyone maintains this project, I do not.

**Comment by marshallswain** [comment]
The problem was actually with my demo.

```html
<section root="true"></section>
<script src="/node_modules/steal/steal.js" main="src/react/buttons/buttons-demo"></script>
```

I had to change the main from the above example to be:

```html
<section root="true"></section>
<script src="/node_modules/steal/steal.js" main="auth-component/react/buttons/buttons-demo"></script>
```

And now everything works.
